### ISSUE TITLE
Release initial version

### ISSUE THREAD

**Issue by nevi-me** [TheDataEngine/mongodb-arrow-connector#3]
We're pulling the below from git, and they'll block pushing an initial release:

```toml
mongodb = { git = "https://github.com/nevi-me/mongo-rust-driver", branch = "decimal-128-hack" }
mongodb-schema-parser = { git = "https://github.com/nevi-me/mongodb-schema-parser", branch = "write-bson", default-features = false }
```

I could exclude schema parser for now, as we'll only need it for #1
